import type { Editor } from 'grapesjs';

/**
 * Carousel behavior — runs inside the canvas iframe AND on published pages.
 * Vanilla JS, no external dependencies. `this` is the carousel root element.
 *
 * Slides are the direct element children that are not generated navigation.
 * Navigation (arrows + dots) is generated by the script so the AI/CMS only has
 * to emit the carousel root and its slides. Autoplay via data-autoplay="<ms>".
 *
 * NOTE: this function is serialized by GrapesJS — keep it self-contained (no
 * closures over module scope) and re-runnable (it rebuilds nav on each run).
 */
function carouselScript(this: HTMLElement) {
  const el = this as HTMLElement & { __sgTimer?: number };

  // Idempotent re-init: drop previously generated nav and timer
  el.querySelectorAll(':scope > .sg-carousel-arrow, :scope > .sg-carousel-dots').forEach((n) => n.remove());
  if (el.__sgTimer) { clearInterval(el.__sgTimer); el.__sgTimer = undefined; }

  const slides = Array.from(el.children) as HTMLElement[];
  if (slides.length === 0) return;

  let current = 0;
  const doc = el.ownerDocument;

  const dotsWrap = doc.createElement('div');
  dotsWrap.className = 'sg-carousel-dots';
  const dots: HTMLElement[] = slides.map((_, i) => {
    const dot = doc.createElement('button');
    dot.type = 'button';
    dot.className = 'sg-carousel-dot';
    dot.setAttribute('aria-label', 'Go to slide ' + (i + 1));
    dot.addEventListener('click', () => goTo(i));
    dotsWrap.appendChild(dot);
    return dot;
  });

  function makeArrow(dir: number, cls: string, label: string, icon: string): HTMLElement {
    const btn = doc.createElement('button');
    btn.type = 'button';
    btn.className = 'sg-carousel-arrow ' + cls;
    btn.setAttribute('aria-label', label);
    btn.innerHTML = icon;
    btn.addEventListener('click', () => goTo(current + dir));
    return btn;
  }

  function goTo(i: number) {
    current = (i + slides.length) % slides.length;
    slides.forEach((s, idx) => { s.style.display = idx === current ? '' : 'none'; });
    dots.forEach((d, idx) => d.classList.toggle('active', idx === current));
  }

  el.appendChild(makeArrow(-1, 'sg-carousel-prev', 'Previous slide', '&#10094;'));
  el.appendChild(makeArrow(1, 'sg-carousel-next', 'Next slide', '&#10095;'));
  if (slides.length > 1) el.appendChild(dotsWrap);
  goTo(0);

  const autoplay = parseInt(el.getAttribute('data-autoplay') || '0', 10);
  if (autoplay > 0 && slides.length > 1) {
    el.__sgTimer = setInterval(() => {
      if (!el.isConnected) { clearInterval(el.__sgTimer); return; }
      goTo(current + 1);
    }, autoplay) as unknown as number;
  }
}

/**
 * Register the sg-carousel + sg-carousel-slide component types.
 * Slides container with prev/next arrows, dot indicators, and optional autoplay.
 */
export function registerCarouselComponent(editor: Editor): void {
  editor.Components.addType('sg-carousel', {
    model: {
      defaults: {
        tagName: 'div',
        droppable: true,
        attributes: { 'data-sg-type': 'carousel' },
        styles: `
          :where([data-sg-type="carousel"]) {
            position: relative;
            width: 100%;
            overflow: hidden;
          }
          .sg-carousel-arrow {
            position: absolute;
            top: 50%;
            transform: translateY(-50%);
            width: 40px;
            height: 40px;
            border: none;
            border-radius: 9999px;
            background: rgba(0, 0, 0, 0.45);
            color: #ffffff;
            font-size: 16px;
            line-height: 1;
            cursor: pointer;
            z-index: 10;
            display: flex;
            align-items: center;
            justify-content: center;
            transition: background 0.2s;
          }
          .sg-carousel-arrow:hover {
            background: rgba(0, 0, 0, 0.7);
          }
          .sg-carousel-prev { left: 14px; }
          .sg-carousel-next { right: 14px; }
          .sg-carousel-dots {
            position: absolute;
            bottom: 14px;
            left: 0;
            right: 0;
            display: flex;
            justify-content: center;
            gap: 8px;
            z-index: 10;
          }
          .sg-carousel-dot {
            width: 10px;
            height: 10px;
            border: none;
            border-radius: 9999px;
            background: rgba(255, 255, 255, 0.45);
            cursor: pointer;
            padding: 0;
            transition: background 0.2s, transform 0.2s;
          }
          .sg-carousel-dot.active {
            background: #ffffff;
            transform: scale(1.2);
          }
        `,
        components: [
          { type: 'sg-carousel-slide' },
          { type: 'sg-carousel-slide' },
          { type: 'sg-carousel-slide' },
        ],
        script: carouselScript,
        traits: [
          { type: 'number', name: 'data-autoplay', label: 'Autoplay (ms, 0 = off)', min: 0, max: 60000 },
        ],
      },
    },
  });

  editor.Components.addType('sg-carousel-slide', {
    model: {
      defaults: {
        tagName: 'div',
        droppable: true,
        draggable: '[data-sg-type="carousel"]',
        attributes: { 'data-sg-type': 'carousel-slide' },
        styles: `
          :where([data-sg-type="carousel-slide"]) {
            width: 100%;
            min-height: 220px;
            padding: 48px 72px;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            text-align: center;
            box-sizing: border-box;
          }
        `,
        components: [
          {
            type: 'sg-heading',
            attributes: { 'data-sg-type': 'heading' },
            tagName: 'h3',
            content: 'Slide title',
          },
          {
            type: 'sg-text',
            attributes: { 'data-sg-type': 'text' },
            content: 'Describe this slide. Replace with a testimonial, product highlight, or feature.',
          },
        ],
      },
    },
  });
}
